### ISSUE TITLE
Adding My Tickets to My Calendar

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-tickets#10]
Hey Joe

I am looking at the integration part of My Calendar with My Tickets.
I am also thinking documentation. I noticed a link in the My Calendar 3.2.0 PDF.
https://docs.joedolson.com/my-tickets/

When activating My Tickets plugin and going to Add Event. 
I see this:
![Screenshot 2021-11-15 at 14 35 15](https://user-images.githubusercontent.com/5323259/141790998-beb68bff-2327-458c-b5bc-273e01ca7388.jpg)

Going to an existing event. I see this:

![Screenshot 2021-11-15 at 14 35 35](https://user-images.githubusercontent.com/5323259/141791080-5d0ecdd4-2dda-4cd4-82ae-810d8bae15dc.jpg)

"View Tickets Purchased for this event" should not be seen before having clicked the "Sell tickets on this event."

**Comment by joedolson** [comment]
Making change so that View Tickets only shows up if there are already tickets sold. Even if sales have been disabled, access to the report is valuable; but showing that when there have never been sales is pointless.
