### ISSUE TITLE
Value 0 in backend payment results in not sending tickets

### ISSUE THREAD

**Issue by JaegersNet** [joedolson/my-tickets#15]
Hi,

when changing a carts total value to 0 (all selected tickets should be sold for free), the tickets aren't sent.

Steps to reproduce:

1. put some tickets in your cart
2. go to the payments section in the WordPress backend
3. change the total value to 0 
4. add name, e-mail etc. and change status to completed and save

This will produce tickets and sends out all relevant e-mails, but they don't contain the links to the QR codes.

BTW: If the total value has been changed to 0, maybe the ticket price on the receipt should also be 0.

Why am I doing this?
I have an event on saturday and sunday. Tickets are available for each day and for the whole weekend. I would like to give someone a one day pass for free, but not for the whole weekend which would be a complimentary ticket.

Best regards,

Michael

**Comment by joedolson** [comment]
Confirmed; I'll work on it!
