### ISSUE TITLE
Custom Field values not shown in report

### ISSUE THREAD

**Issue by leph83** [joedolson/my-tickets#17]
Adding custom fields as described in the documentation doesn't show them in the reports page

I've added the custom fields like in your github repository
https://github.com/joedolson/plugin-extensions/blob/master/my-tickets/my-tickets-custom-fields.php

The fields are showing in the order as expected. The report also shows the custom fields in the header, but the values for each custome field for each customer who bought the ticket is missing. 

It seems like the data isn't stored correctly since "get_post_meta" don't show the custom fields.

**Comment by joedolson** [comment]
Is this the same as issue #14? Do the custom fields save properly when you're logged in?

**Comment by leph83** [comment]
No, I don't think it's the same problem. The custom field is properly saved as far as I can tell. 
The content is shown in the report per event but not per data.
