### ISSUE TITLE
Popup Notification

### ISSUE THREAD

**Issue by fahadx4** [joedolson/my-tickets#20]
**Popup Notification**
When people try to reserve a ticket a popup appear asking to leave a site? changes wont be saved. 

**Screenshots**
<img width="1029" alt="Screenshot_41" src="https://user-images.githubusercontent.com/73199397/209191026-c99164c4-e4f6-45c6-9f63-94b85ef99f5a.png">

**Comment by joedolson** [comment]
I think that I fixed this some time ago, but failed to close the issue. If this is still a problem, feel free to comment.
